### ISSUE TITLE
Bug when highlighting special characters.

### ISSUE THREAD

**Issue by Alexhrywkiw** [vim-zz/StickySearch#4]
When attempting to highlight certain special characters the entire selection including the characters is not highlighted or they are only able to have text highlighted if they are the last character in the selected text.

List of Characters that seem to have odd interactions:

$
^
+
*
Also open and closed brackets are not highlighted when selecting both the opened and closed ( ) , [ ]

**Comment by vim-zz** [comment]
it's about time 🙃 fixed with latest version 1.1.1
